routes/web.php
<?php

use App\Http\Controllers\Web\AuthConroller;
use App\Http\Controllers\Web\CartController;
use App\Http\Controllers\Web\Cms\CmsController;
use App\Http\Controllers\Web\GuitarController;
use App\Http\Controllers\Web\OrderController;
use App\Http\Controllers\Web\SearchController;
use Illuminate\Auth\Events\Login;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// using template
Route::get('/cms',[CmsController::class,'index']);




// using blade without template
Route::get('/login', function () {
    return view('ui.login');
});
Route::get('/register', function () {
    return view('ui.register');
});
Route::get('/logout', function () {
    Session::forget('user');
    return redirect('/login');
});
Route::get('/store', function () {
    return view('ui.store');
});

Route::post('/login',[AuthConroller::class,'login']);
Route::post('/register',[AuthConroller::class,'register']);

Route::get('/search',[SearchController::class,'search']);
Route::resource('/guitar',GuitarController::class);
Route::post('/addtocart',[CartController::class,'addToCart']);
Route::get('/cartlist',[CartController::class,'cartList']);
Route::get('/removecart/{id}',[CartController::class,'removeCart']);
Route::get('/ordernow',[OrderController::class,'orderNow']);
Route::post('/orderplace',[OrderController::class,'orderPlace']);
Route::get('/myorder',[OrderController::class,'myOrder']);
Route::get('/removeorder/{id}',[OrderController::class,'removeOrders']);

resources/views/ui/cartlist.blade.php
@extends('ui.master')
@section('content')
    <div class="custom-product">
        <div class="col-sm-12">
            <div class=""> 
                <a href="/guitar">Go Back</a>
                <h2>Cart List</h2>
                <div class="">
                    @foreach ($data as $item)
                        <div class="row search-item cart-list-devider">
                            <div class='col-sm-4'>
                                <a href="pdetail/{{$item->id}}">
                                    <img class='cart-img' src="{{$item->gallery}}">
                                </a>
                            </div>
                            <div class='col-sm-4'>
                                    <div class="">
                                        <h2>{{$item->name}}</h2>
                                        <h5>{{$item->description}}</h5>
                                    </div>
                            </div>
                            <div class='col-sm-4'>
                                <a href="/removecart/{{$item->cart_id}}" class='btn btn-warning'>Remove from Cart</a>
                            </div>
                            </div>
                        </div> 
                    @endforeach
                    <a class='btn btn-success' href='/ordernow'>Order Now</a> <br> <br>
                </div>
            </div> 
        </div>
    </div>
@endsection

resources/views/ui/footer.blade.php
<div style="clear:both" class="panel panel-default">
    <div class="panel-body">A Basic Panel</div>
  </div>

resources/views/ui/header.blade.php
@php
    use App\Http\Controllers\Web\CartController;
    $total=0;
    if(Session::has('user')){
        $total = CartController::cartItem();
    }
    
@endphp
<nav class="navbar navbar-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/guitar">GuitarShop</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="/guitar">Home</a></li>
        </ul>
        <form action='/search' class="navbar-form navbar-left" action="/action_page.php">
            <div class="form-group">
                <input type="text" name='query' class="form-control search-box" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
            @if (Session::has('user'))
            <li><a href="/store">Add Guitars</a></li>
            <li><a href="/myorder">orders</a></li>
            <li><a href="/cartlist">cart({{ $total }})</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ Session::get('user')['name'] }}
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/logout">Logout</a></li>
                    </ul>
                </li>
            @else
                <li><a href="/login">Login</a></li>
                <li><a href="/register">register</a></li>
            @endif
        </ul>
    </div>
</nav>

resources/views/ui/login.blade.php
@extends('ui.master')
@section('content')
<div class="container custom-login">
    <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
        <form action='login' method='POST'>
            <div class="mb-3">
                @csrf
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
            </div>
            {{-- <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Keep Me Loged</label>
            </div> --}}
            <br>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
    </div>
</div>
    
@endsection

resources/views/ui/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>E-comm Project</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
     {{-- {{View::make('ui.header')}} --}}
    @include('ui.header')
    @yield('content')
    @include('ui.footer')
    {{-- {{View::make('ui.footer')}} --}}


    

</body>
<style>
    .custom-login{
        height: 500px;
        padding-top: 100px;

    }
    img.slider-img{
        height: 400px !important;
    }
    .custom-product{
        height: 600px;
    }
    .slider-text{
        background-color: rgb(182 166 166 / 8%);
    }
    .image-detail{
        height: 200px;
    }
    .searched-item{
        height: 100px;
    }
    .cart-list{
        float: left;
        width: 20%
    }
    .cart-img{
        height: 100px;
    }
    .cart-wrapper{
        margin: 25px;
    }
    .cart-list-devider{
        border-bottom: 1px solid #cccccc;
        margin-bottom: 10px;
        padding-bottom: 10px;
    }
    .trending-item{
        float: left;
        width: 20%;
    }
    .Trending-wrapper{
        margin: 25px;
    }
    .detail-img{
        height: 200px; 
    }
    .search-box{
        width: 500px !important;
    }
</style>
    
</html>

resources/views/ui/myorder.blade.php
@extends('ui.master')
@section('content')
    <div class="custom-product">
        <div class="col-sm-10">
            <div class="">
                <a href="/guitar">Go Back</a>
                <h2>My Orders</h2>
                <div class="">
                    @foreach ($data as $item)
                        <div>
                            <div class="row search-item cart-list-devider">
                                <div class='col-sm-4'>
                                    <a href="/guitar {{ $item->id }}">
                                        <img class='cart-img' src="{{ $item->gallery }}">
                                    </a>
                                </div>
                                <div class='col-sm-4'>
                                    <div class="">
                                        <h2>{{ $item->name }}</h2>
                                        <h5>{{ $item->price }}</h5>
                                        <h5>{{ $item->type }}</h5>
                                        <h5>{{ $item->description }}</h5>
                                        <h5>{{ $item->order_status }}</h5>
                                        <h5>Uder ID {{ $item->user_id }}</h5>
                                        <h5>{{ $item->id }}</h5>
   
                                    </div>
                                </div>
                                <div class='col-sm-4'>
                                    <a href="/removeorder/{{$item->id}}" class='btn btn-warning'>Remove from order</a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ui/ordernow.blade.php
@extends('ui.master')
@section('content')
    <div class="custom-product">
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tbody>
                  <tr>
                    <td>Price</td>
                    <td> $ {{$data}} </td>
                  </tr>
                  <tr>
                    <td>Tax</td>
                    <td> $ {{$data/100}} </td>
                  </tr>
                  <tr>
                    <td>Delivery</td>
                    <td>$ 20</td>
                  </tr>
                    <td>Total Amount</td>
                    <td>$ {{$data+20}}</td>
                  </tr>
                </tbody>
            </table>

              <form method='POST' action="orderplace">
                @csrf
                <div class="form-group">
                  <textarea placeholder='enter your address' name='address' class="form-control"> </textarea>
                </div>
                <div class="form-group">
                    <label for="">Payment Method</label>
                  <p><input type="radio" value="cash" name="payment"> <span> Online Payment</span></p>
                  <p><input type="radio" value="cash" name="payment"> <span> Efts On Delivery</span></p>
                  <p><input type="radio" value="cash" name="payment"> <span> Cash on Delivery Payment</span></p>
                </div>
                <button type="submit" class="btn btn-default">Order Now</button>
              </form>

        </div>
    </div>
@endsection

resources/views/ui/pdetail.blade.php
@extends('ui.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <img class="image-detail" src="{{ $guitar['gallery'] }}" alt="">
            </div>
            <div class="col-sm-6">
                <a href="/guitar">Go back</a>
                <h2>Name: {{ $guitar['name'] }}</h2>
                <h3>Price: {{ $guitar['price'] }}</h3>
                <h4>Type: {{ $guitar['type'] }}</h4>
                <h4>Description: {{ $guitar['description'] }}</h4>
                <h4>Warranty: {{ $guitar['Warranty'] }}</h4>
                <h4>Available Stock: {{ $guitar['reamaining_quantity'] }}</h4>
                <br><br>
                <form action="/addtocart" method="POST">
                    <input type="hidden" name="guitar_id" value="{{$guitar['id']}}">
                    @csrf
                    <button class="btn btn-success ">Add to Cart</button>
                </form>
                <br><br>
                <button class="btn btn-primary ">Buy Now</button>
                <br><br>
            </div>
        </div>
    </div>
@endsection

resources/views/ui/product.blade.php
@extends('ui.master')
@section('content')
    <div class="custom-product">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                @foreach ($guitar as $item)
                    <div class="item {{ $item['id'] == 1 ? 'active' : '' }}">
                        <a href="guitar/{{ $item['id'] }}">
                            <img class='slider-img' src="{{ $item['gallery'] }}" alt="pic">
                            <div class="carousel-caption slider-text">
                                <h3>{{ $item['name'] }}</h3>
                                <p>{{ $item['description'] }}</p>
                            </div>
                        </a>

                    </div>
                @endforeach

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    @if (Session::has('user'))
        <div class="col-sm-12">
            <div class="">
                <h2>Guitar List</h2>
                <div class="">
                    @foreach ($guitar as $item)
                        <div class="row search-item cart-list-devider">
                            <div class='col-sm-4'>
                                <a href="pdetail/{{ $item->id }}">
                                    <img class='cart-img' src="{{ $item->gallery }}">
                                </a>
                            </div>
                            <div class='col-sm-4'>
                                <div class="">
                                    <h2>{{ $item->name }}</h2>
                                    <h5>{{ $item->description }}</h5>
                                    <h5>{{ $item->type }}</h5>
                                    <h5>{{ $item->price }}</h5>
                                    <h5>{{ $item->reamaining_quantity }}</h5>
                                </div>
                            </div>
                            <div class='col-sm-4'>
                                <form action="{{ route('guitar.destroy', $item->id) }}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class='btn btn-warning'>Delete Guitar</button>
                                </form>
                            </div>
                        </div>
                </div>
                @endforeach
                <a class='btn btn-success' href='/ordernow'>Order Now</a> <br> <br>
            </div>
        </div>

    @endif
    </div>
@endsection

resources/views/ui/register.blade.php
@extends('ui.master')
@section('content')
<div class="container custom-login">
    <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
    
    @if ($errors->any())
  
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach


    @endif
        <form action='register' method='POST'>
            @csrf
            <div class="form-group">
            <label for="name" class="form-label">Name</label>
            <input type="text" name="name" placeholder="Enter your name" class="form-control" id="name">
            </div>
            <div class="form-group">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" name="email" placeholder="Enter your email" class="form-control" id="exampleInputEmail1">
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" placeholder="Enter your password" class="form-control" id="exampleInputPassword1">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">submit</button>
        </form>
    </div>
    </div>
</div>
    
@endsection

resources/views/ui/search.blade.php
@extends('ui.master')
@section('content')
    <div class="container custom-product">
        <div class="row">
            <div class="col-sm-6">
                @foreach ($data as $item)
                    <a href="guitar/{{ $item['id'] }}">
                        <img class="searched-item" src="{{ $item['gallery'] }}" alt="">
                        <div class="">
                            <h4>{{ $item['name'] }}</h4>
                            <h4>{{ $item['description'] }}</h4>
                        </div>
                    </a>
                @endforeach
            </div>       
        </div>      
    </div>
@endsection

resources/views/ui/store.blade.php
@extends('ui.master')
@section('content')
    <!------ Include the above in your HEAD tag ---------->
    {{-- @if ($errors->any())
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
    @endif --}}
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    <div> 
        <form class="form-horizontal" action="{{ route('guitar.store') }}" method='POST'>
            @csrf
            <fieldset>
                <!-- Form Name -->
                <legend>PRODUCTS</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="name">PRODUCT NAME</label>
                    <div class="col-md-4">
                        <input id="product_name" name="name" placeholder="PRODUCT NAME" class="form-control input-md"
                            type="text">

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="name">PRODUCT TYPE</label>
                    <div class="col-md-4">
                        <input id="type" name="type" placeholder="PRODUCT TYPE" class="form-control input-md"
                            type="text">
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="description">PRODUCT PRICE</label>
                    <div class="col-md-4">
                        <input id="price" name="price" placeholder="price" class="form-control input-md"
                            type="text">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="total_quantity">AVAILABLE QUANTITY</label>
                    <div class="col-md-4">
                        <input id="total_quantity" name="total_quantity" placeholder="AVAILABLE QUANTITY"
                            class="form-control input-md" type="text">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="Warranty">PRODUCT WARRANTY</label>
                    <div class="col-md-4">
                        <input id="Warranty" name="Warranty" placeholder="PRODUCT WEIGHT" class="form-control input-md"
                            type="text">

                    </div>
                </div>

                <!-- Textarea -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="description">PRODUCT DESCRIPTION</label>
                    <div class="col-md-4">
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </div>


                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="comment">Gallery</label>
                    <div class="col-md-4">
                        <input id="gallery" name="gallery" placeholder="insert image link" class="form-control input-md"
                            type="text">

                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="singlebutton">Single Button</label>
                    <div class="col-md-4">
                        <button id="singlebutton" name="singlebutton" class="btn btn-primary">Add Product</button>
                    </div>
                </div>

            </fieldset>
        </form>


    </div>
@endsection




<!-- File Button -->
{{-- <div class="form-group">
  <label class="col-md-4 control-label" for="filebutton">main_image</label>
  <div class="col-md-4">
    <input id="filebutton" name="filebutton" class="input-file" type="file">
  </div>
</div> --}}